micronaut:
  application:
    name: demo
netty:
  default:
    allocator:
      max-order: 3
r2dbc:
  datasources:
    default:
      dialect: POSTGRES
      url: r2dbc:postgresql://localhost:5432/test
      username: test_user
      password: test_password
